=== jbianchi81/pydrodelta/schemas/json/topology.json
{
  "$id": "topology.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Topology",
  "type": "object",
  "description": "The topology defines a list of nodes which represent stations and basins. These nodes are identified with a node_id and must contain one or many variables each, which represent the hydrologic observed/simulated properties at that node (such as discharge, precipitation, etc.). They are identified with a variable_id and may contain one or many ordered series, which contain the timestamped values. If series are missing from a variable, it is assumed that observations are not available for said variable at said node. Additionally, series_prono may be defined to represent timeseries of said variable at said node that are originated by an external modelling procedure. If series are available, said series_prono may be automatically fitted to the observed data by means of a linear regression. Such a procedure may be useful to extend the temporal extent of the variable into the forecast horizon so as to cover the full time domain of the plan. Finally, one or many series_sim may be added and it is where simulated data (as a result of a procedure) will be stored. All series have a series_id identifier which is used to read/write data from data source whether it be an alerta5DBIO instance or a csv file.",
  "properties": {
    "timestart": {
      "description": "start date of observations period (datetime or timedelta relative to now)",
      "$ref": "dateorinterval.json"
    },
    "timeend": {
      "description": "end date of observations period (datetime or timedelta relative to now)",
      "$ref": "dateorinterval.json"
    },
    "forecast_timeend": {
      "description": "forecast horizon (datetime or timedelta relative to timeend)",
      "$ref": "dateorinterval.json"
    },
    "time_offset": {
      "description": "time of day where timesteps start",
      "$ref": "dateorinterval.json"
    },
    "time_offset_start": {
      "description": "time of day where first timestep starts",
      "$ref": "dateorinterval.json"
    },
    "nodes": {
      "description": "information nodes of the topology",
      "type": "array",
      "items": {
        "$ref": "node.json"
      }
    },
    "analysis": {
      "description": "analysis actions to perform",
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "concatenateProno",
          "uploadData"
        ]
      }
    },
    "cal_id": {
      "type": "integer"
    },
    "plot_params": {
      "$ref": "plotparams.json"
    },
    "plot_variable": {
      "type": "array",
      "description": "Print graphs of selected variables for each node where said variables are defined, and save into pdf multipage files (one file per variable, one page per node)",
      "items": {
        "type": "object",
        "properties": {
          "var_id": {
            "type": "integer",
            "description": "Variable identifier"
          },
          "output": {
            "type": "string",
            "description": "Output file path"
          },
          "timestart": {
            "$ref": "dateorinterval.json"
          },
          "timeend": {
            "$ref": "dateorinterval.json"
          },
          "extra_sim_columns": {
            "type": "boolean"
          }
        },
        "required": [
          "var_id",
          "output"
        ]
      }
    },
    "interpolation_limit": {
      "description": "maximum duration between observations for interpolation",
      "$ref": "timeinterval.json"
    },
    "extrapolate": {
      "description": "Extrapolate observations outside the observation time domain, up to a maximum duration equal to interpolation_limit",
      "type": "boolean"
    },
    "report_file": {
      "description": "Write analysis report into this file",
      "type": "string"
    },
    "no_metadata": {
      "description": "Don't retrieve series metadata on loading from api",
      "type": "boolean",
      "default": false
    },
    "include_prono": {
      "description": "While executing .batchProcessInput, use series_prono to fill nulls of series",
      "type": "boolean",
      "default": false
    },
    "output_csv": {
      "description": "Save analysis results as csv into this path (relative to PYDRODELTA_DIR)",
      "type": "string"
    },
    "output_json": {
      "description": "Save analysis results as json into this path (relative to PYDRODELTA_DIR)",
      "type": "string"
    },
    "pivot": {
      "description": "If output_csv is set, pivot series into columns of the table",
      "type": "boolean",
      "default": true
    },
    "pretty": {
      "description": "For output_json, prettify json",
      "type": "boolean",
      "default": true
    },
    "upload_prono": {
      "description": "upload series_prono",
      "type": "boolean",
      "default": false
    },
    "qualifiers": {
      "description": "Add these qualifiers to the series_prono upload. Use together with upload_prono",
      "type": "array",
      "items": {
        "type": "string"
      },
      "examples": [
        [],
        ["inferior", "superior"]
      ]
    },
    "save_response": {
      "description": "Save forecast creation response into this file. Use together with upload_prono"
    },
    "save_post_data": {
      "description": "Save forecast creation request data into this file. Use together with upload_prono"
    }
  },
  "required": [
    "timestart",
    "timeend",
    "nodes"
  ],
  "additionalProperties": false
}

=== jbianchi81/pydrodelta/data/topologies/bajo_uruguay.json
{
    "$schema": "../schemas/topology.json",
    "timestart": {"days":-15},
    "timeend": {"hours":0},
    "forecast_timeend": {"days": 5},
    "time_offset_start": {"hours": 0},
    "nodes": [
        {
            "id": 1,
            "name": "Salto Grande - Flow hydrograph - 1H",
            "hec_node": {
                "River": "Uruguay",
                "Reach": "Bajo",
                "River_Stat": 1151708,
                "Interval": "1HOUR",
                "CondBorde": "Folw Hydrograph"
            },
            "series": [
                {
                    "series_id": 927,
                    "lim_outliers": [
                        0,
                        40000
                    ],
                    "lim_jump": 15000,
                    "x_offset": 0,
                    "y_offset": 0
                }
            ],
            "series_prono": [
                {
                    "series_id": 7833,
                    "lim_outliers": [
                        0,
                        40000
                    ],
                    "lim_jump": 15000,
                    "x_offset": 0,
                    "y_offset": 0,
                    "comment": "tabprono Bajo Uruguay",
                    "cal_id": 485,
                    "qualifier": "medio",
                    "adjust": false
                }
            ],
            "time_interval": {
                "hours": 1
            },
            "time_offset": null,
            "interpolation_limit": 48,
            "output_series_id": 31571,
            "adjust_prono": true
        },
        {
            "id": 2,
            "name": "Nueva Palmira - Stage Hydrograph -1H",
            "hec_node": {
                "River": "Uruguay",
                "Reach": "Bajo",
                "River_Stat": 16577,
                "Interval": "1HOUR",
                "CondBorde": "Stage Hydrograph"
            },
            "series": [
                {
                    "series_id": 3280,
                    "lim_outliers": [
                        -1.7,
                        3.42
                    ],
                    "lim_jump": 0.4,
                    "x_offset": 0,
                    "y_offset": 0.0275
                },
                {
                    "series_id": 2111,
                    "lim_outliers": [
                        -2.01,
                        2.66
                    ],
                    "lim_jump": 0.5,
                    "x_offset": 0,
                    "y_offset": 0
                }
            ],
            "series_prono": [
                {
                    "series_id": 26203,
                    "lim_outliers": [
                        -1.7,
                        3.42
                    ],
                    "lim_jump": 0.4,
                    "x_offset": 0,
                    "y_offset": 0.0275,
                    "comment": "N Palmira prono regre",
                    "cal_id": 433,
                    "adjust": true
                }
            ],
            "time_interval": {
                "hours": 1
            },
            "time_offset": null,
            "output_series_id": 31555
        }
    ]
}

=== jbianchi81/pydrodelta/data/topologies/gualeguay_rt_dummy.json
{
    "timestart": {"days":-90},
    "timeend": {"days":7},
    "forecast_timeend": {"days": 0},
    "time_offset_start": {"hours": 9},
    "nodes": [
        {
            "id": 1,
            "name": "Gualeguay@RT - PMA - 1D",
            "series": [
                {
                    "series_id": 232,
                    "tipo": "areal",
                    "lim_outliers": [
                        -0.0000001,
                        200
                    ],
                    "comment": "pmad campo interpolado. area_id=2"
                },
                {
                    "series_id": 8,
                    "tipo": "areal",
                    "lim_outliers": [
                        -0.0000001,
                        200
                    ],
                    "comment": "pmad análisis cpc. area_id=2"
                },
                {
                    "series_id": 176,
                    "tipo": "areal",
                    "lim_outliers": [
                        -0.0000001,
                        200
                    ],
                    "comment": "pmad gfs. area_id=2"
                }
            ],
            "time_interval": {
                "days": 1
            },
            "time_offset": null,
            "output_series_id": null,
            "adjust_prono": false
        },
        {
            "id": 2,
            "name": "Gualeguay@RT - ETP - 1D",
            "series": [
                {
                    "series_id": 120,
                    "tipo": "areal",
                    "lim_outliers": [
                        0,
                        8
                    ],
                    "comment": "etp climatológica wm. area_id=2"
                }
            ],
            "time_interval": {
                "days": 1
            },
            "time_offset": null,
            "interpolation_limit": 6,
            "output_series_id": null,
            "adjust_prono": false
        },
        {
            "id": 3,
            "name": "Gualeguay@RT - SM - 1D",
            "series": [
                {
                    "series_id": 1625,
                    "tipo": "areal",
                    "lim_outliers": [
                        0,
                        0.99
                    ],
                    "comment": "sm smops. area_id=2"
                }
            ],
            "time_interval": {
                "days": 1
            },
            "time_offset": null,
            "interpolation_limit": 2,
            "output_series_id": null,
            "adjust_prono": false
        },
        {
            "id": 4,
            "name": "Gualeguay@RT - Q - 1D",
            "series": [
                {
                    "series_id": 7806,
                    "tipo": "puntual",
                    "lim_outliers": [
                        0,
                        5000
                    ],
                    "comment": "Q obs Rosario del Tala-RHN (telemétrica) estacion_id=2203"
                }
            ],
            "series_sim": [
                {
                    "series_id": 31609,
                    "tipo": "puntual",
                    "comment": "Q sim diario Rosario del Tala-RHN (telemétrica) estacion_id=2203"
                }
            ],
            "time_interval": {
                "days": 1
            },
            "time_offset": null,
            "output_series_id": null,
            "adjust_prono": false
        }
    ]
}
